# see https://github.com/ndmitchell/hlint/issues/572#issuecomment-464752600
- arguments:
    - -XNoImplicitPrelude
    - -XOverloadedStrings
    - -XLambdaCase
    - -XBlockArguments
    - -XBangPatterns
    - -XTupleSections
    - -XScopedTypeVariables
